Now font family are same
smaranjitghose/awesome-portfolio-websites pull request #1029
Opened 2021-08-03 08:11 UTC by ArihantJain123

I change all font family and now all font family style is same.

2021-08-04 01:39 UTC, smaranjitghose requested changes

2021-08-04 01:39 UTC, smaranjitghose commented on travel_temp.html
>          <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
This is a straightforward task. You were supposed to just replace the font family. (Check Line 41 below. Not satisfied)

2021-08-04 01:39 UTC, smaranjitghose commented on research.html
>      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300&display=swap" rel="stylesheet">
Why is Poppins still being fetched?

2021-08-04 01:39 UTC, smaranjitghose commented on research.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
Please be mindful of the indentation

2021-08-04 01:39 UTC, smaranjitghose commented on assets/css/style.css
> +    font-family: 'Noto Serif', serif;
This font was not specified anywhere and does not go well with the UI at all

2021-08-04 01:41 UTC, smaranjitghose commented
Please follow the Contributing.MD for the PR description

2021-08-04 06:11 UTC, ArihantJain123 commented
Now I have completed the changes in head branch please you will review my changes.

2021-08-05 05:43 UTC, smaranjitghose commented
Use the font specified in the issue description please

2021-08-05 10:56 UTC, ArihantJain123 commented
Now I have change the font family you review the changes.

2021-08-05 11:09 UTC, smaranjitghose commented on assets/css/cursor.css
> +  font-family: 'Frank Ruhl Libre', serif;
Why is this required for the cursor style?

2021-08-05 11:09 UTC, smaranjitghose commented on assets/css/research.css
> +  font-family: 'Frank Ruhl Libre', serif;
See the first line of the stylesheet.

2021-08-05 11:10 UTC, smaranjitghose commented
Too many changes for a simple PR. If we had to go through all of them, we would have done it ourselves.

2021-08-05 11:10 UTC, closed without merging