Volunteering section modified
smaranjitghose/awesome-portfolio-websites pull request #110
Opened 2020-08-24 05:03 UTC by raksha009

Made the following changes:
1. Added new images in the experience section folder itself
2. Added new animations

Issue #80

2020-08-24 05:04 UTC, raksha009 commented
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/57195964/91005802-60ae3800-e5f5-11ea-8b95-9d95ccc9ef77.gif)

2020-08-24 13:52 UTC, smaranjitghose commented
Volunteering is something, we usually do out of passion. So, having a dedicated view certificate link to prove it seems odd
@anushbhatia will suggest you changes for the animation

2020-08-24 13:54 UTC, smaranjitghose requested changes

2020-08-24 13:54 UTC, smaranjitghose commented on experience.html
> +            <p>Responsible for handling the projects GirlScript App and GirlScript Website Boilerplate.</p>
Isn't this  supposed to be loaded from a script?

2020-08-24 13:54 UTC, smaranjitghose commented on experience.html
> +<!--    <script src="assets/js/experience.js"></script>-->
???

2020-08-24 17:11 UTC, raksha009 commented
Okay, I'll remove that view certificate option.
Also, I commented out the Js part cause the images weren't loading up (or showing ) in pc. So, the same issue persisted even when I tried uploading images via css too. 
Moreover, I wasn't able to change animation when the text was uploading from JS part. So, hence tried putting all display part in html.

2020-09-01 16:48 UTC, raksha009 commented
@smaranjitghose @anushbhatia plz suggest

2020-09-04 14:50 UTC, anushbhatia commented
Don't upload images with the help of the CSS use HTML for that. See use main.js where you store the data for different images and the text. In the HTML just load the data form that file so that if we add a new volunteering experience it automatically gets added.

2020-09-11 07:10 UTC, shreyakapoor08 commented
@raksha009 Resolve the merge conflict

2020-09-11 08:54 UTC, closed without merging