Set Default to Dark Mode #1148
smaranjitghose/awesome-portfolio-websites pull request #1158
Opened 2022-01-19 06:59 UTC by gourangi-taware

I have added light-mode as "dark" in each of the pages so that the default theme becomes dark. For making the light theme consistent while navigating through pages, I have made some changes in app.js as follows
![image](https://user-images.githubusercontent.com/68667929/150079908-405acfa5-4a16-451c-9354-a53f1b34f12d.png)

2022-01-20 01:10 UTC, anushbhatia requested changes
Once you switch from dark mode to light mode the navbar becomes white completely.
![image](https://user-images.githubusercontent.com/40017559/150244082-b2e93649-7bd5-4624-bf2c-ac507f447410.png)
here's a sample

2022-01-20 04:58 UTC, gourangi-taware commented
Okay, I'll update the code accordingly.

2022-01-20 05:22 UTC, gourangi-taware commented
I checked the code and the integration, but the case where the navbar is becoming white is only for the Experience page. It is working fine with all the other pages. I made changes only in app.js (globally) and only changed the theme for respective pages. I am trying to understand the reason but I am unable to find the exact error. Can you please guide me to resolve the issue?  Following are some of the samples of the working:

![image](https://user-images.githubusercontent.com/68667929/150277910-567a08ec-2387-48cd-96a5-3d45962137ca.png)
![image](https://user-images.githubusercontent.com/68667929/150277939-6d0802f9-3858-4e0f-8ce6-a00d721ddb25.png)
![image](https://user-images.githubusercontent.com/68667929/150277970-d851ca81-ae30-4562-9635-ebfefef48eae.png)

2022-01-20 05:46 UTC, anushbhatia reviewed
Check the css code for experience.css 
https://github.com/smaranjitghose/awesome-portfolio-websites/pull/992/files this might have caused this issues

2022-01-20 06:07 UTC, gourangi-taware commented
I have made the necessary changes and committed the changes
![image](https://user-images.githubusercontent.com/68667929/150283016-a92d47a0-eb5f-4dd1-a5af-e7e397cefc0f.png)
![image](https://user-images.githubusercontent.com/68667929/150283064-b9efdc19-e5ae-4a66-a1c0-4299835da8b6.png)
Please review the changes

2022-01-20 12:14 UTC, anushbhatia requested changes

2022-01-20 12:14 UTC, anushbhatia commented on assets/css/experience.css
> +  /* color: white; */
remove unused text it won't be any good here.

2022-01-20 18:50 UTC, gourangi-taware commented
I have done the required changes. Please review

2022-01-21 18:25 UTC, merged

2022-01-21 18:26 UTC, anushbhatia commented
great work @gourangi-taware  and keep it up.