Updated reference page
smaranjitghose/awesome-portfolio-websites pull request #1183
Opened 2022-02-10 02:45 UTC by Shruti025

Issue: #1168 

-Fixed the bug
-Made the required name and image changes in the cards.

2022-02-10 09:13 UTC, anushbhatia reviewed
![image](https://user-images.githubusercontent.com/40017559/153375027-85160b06-7beb-447c-a523-94e4d30c1eb7.png)
Mobile view the images are getting squished (the ratio of image is changed)

2022-02-10 16:45 UTC, smaranjitghose requested changes

2022-02-10 16:45 UTC, smaranjitghose commented on assets/js/references.js
>        "I had worked with John in research intern team, Flipkart. John would be an asset to have on any team. To say he's a team leader would be an understatement. during his tenure at our company, he
Can you please remove the unused code

2022-02-11 11:57 UTC, Shruti025 commented
I'll work on the reviews today and submit a PR by tomorrow

2022-02-15 08:16 UTC, anushbhatia commented
Will create another issue for responsiveness

2022-02-15 08:16 UTC, merged