Dark mode of Home page and experience page
smaranjitghose/awesome-portfolio-websites pull request #132
Opened 2020-09-10 08:16 UTC by Adyasha8105

I have made the page suitable for both modes.
Also done minute changes :) to make the site perfect.

@anushbhatia @smaranjitghose Have a look.

2020-09-10 09:02 UTC, smaranjitghose requested changes

2020-09-10 09:02 UTC, smaranjitghose commented on experience.html
> +    <h6 class="text-center py-2 heading2">These are an amazing oppurtunity to boost up your tech stack.</h6>
Remove this

2020-09-10 09:02 UTC, smaranjitghose commented on experience.html
> +    <h6 class="text-center py-2 heading2">I have been mentoring various projects for various organizations thourugh the skills
Remove this

2020-09-10 09:02 UTC, smaranjitghose commented on experience.html
> +            <h2 style="font-size: 3em;font-weight: bolder; color: var(--text);" class="mb-0">Experience</h2>
avoid inline css at all costs

2020-09-10 09:02 UTC, smaranjitghose commented on assets/js/main.js
> +<div class="nav-wrapper" style="margin: 0 20px 0 20px">
Comments please. Remember our code should be readable to others as well

2020-09-10 12:38 UTC, Adyasha8105 commented on experience.html
> +    <h6 class="text-center py-2 heading2">These are an amazing oppurtunity to boost up your tech stack.</h6>
Remove all the heading part??

2020-09-10 18:19 UTC, Adyasha8105 commented
@smaranjitghose Is it okay now?

2020-09-11 07:23 UTC, merged

2020-09-11 07:24 UTC, shreyakapoor08 reviewed
looks fine now

2020-09-11 07:53 UTC, smaranjitghose commented
Fix these bugs please
![exp_bug](https://user-images.githubusercontent.com/46641503/92887135-e1609700-f431-11ea-87ff-43cac2ef3118.jpg)
![exp_bug_2](https://user-images.githubusercontent.com/46641503/92887147-e3c2f100-f431-11ea-9a5d-1e892472db52.jpg)