Added contributing guidelines
smaranjitghose/awesome-portfolio-websites pull request #165
Opened 2020-09-19 09:48 UTC by shraddhavp

solves issue #156 
Contributing Guidelines added

2020-09-19 09:49 UTC, shraddhavp commented
@smaranjitghose  sir please do let me know if any changes needed

2020-09-19 18:09 UTC, smaranjitghose requested changes

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +<h2 align="center"><b>Pull Request Process</b></h2>
Make it as "How to make a Pull Request?"
Try to follow it up with a GIF

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**2.**  Clone the forked repository.
Clone your forked copy of the project

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +   <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT5N0HJ9db7jSvcL4dsDscZQBzqQqqKVs0BnO1OVz26glLWKJRY&usqp=CAU" width="300">
Put these images inside the assets folder and put the relative path, please.

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +git remote add upstream  https://github.com/smaranjitghose/awesome-portfolio-websites.git (url of the repository)
Remove the bracket and it's content otherwise people will copy and paste it in the terminal directly

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**5.** See latest  changes to the repo using
Check the remotes for this repository

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +git pull upstream master
First we should pull from upstream and then create a feature branch. Swap 7 and 6 please

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**8.** Make changes in the source code after getting yourself assigned to the issue by the mentors/developers of the project.
Perfom your desired changes to the code base

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**9.** Add and then commit your changes.
9. Track your changes

`git add .`

10. Commit Your changes

`git commit -m "Relevant Message"`

VV
Adjust the order of bullet points accordingly

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**10.** Push your local branch to the remote repository.
Push the committed changes in your feature branch to your remote.....

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**12.** Finally, go to your repository in browser and click on `compare and pull requests`.
11. and 12. Should be combined like:

 " To create a pull request, click on `compare and pull request`.  Please ensure you compare your feature branch to the desired branch of the repo you are suppose to make a PR to. "

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +**13.** Then add an appropriate title and description to your pull request that explains your changes and efforts done.
You are requested to Add a short and appropriate title, reference the issue, give an elaborate description of your work and attach screenshots of the same

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +
15. Voila! You have made a PR to the awesome-developer-portfolio project. Sit back patiently and relax while the project maintainers review your PR. Please understand at times the time can vary from a few hours to a few days

2020-09-19 18:09 UTC, smaranjitghose commented on CONTRIBUTING GUIDELINES.md
> +
This is not required here.

2020-09-19 18:11 UTC, smaranjitghose commented
@shraddhavp 
# Suggested Changes:
- Please try to put emojis in the instructions as well.  You can have a look at my other repos for reference. 
- For the images try to take the screenshots of this repo itself and put it inside the assets folder and use a relative path
- Please make the content changes as suggested above

2020-09-20 05:38 UTC, shraddhavp commented
yes sir will do it

2020-09-20 05:38 UTC, shraddhavp commented
will close this PR and create a new one with the changes

2020-09-20 05:39 UTC, closed without merging