added resume section
smaranjitghose/awesome-portfolio-websites pull request #406
Opened 2021-01-01 15:54 UTC by Abhijay007

# Related Issues or bug
  - Info about Issue or bug
    Feature request: instead of directly redirecting the viewer to the drive link, give the option to download and view the resume
Fixes: #387 

# Proposed Changes
 - Info about changes Goes here
   added resume section to the home page and provided download and view option for the same 
# Screenshots

 Original          
 
![original](https://user-images.githubusercontent.com/64387054/103441938-9801b500-4c77-11eb-8bd9-500a5d23f867.gif)

updated

![updated](https://user-images.githubusercontent.com/64387054/103441952-a8199480-4c77-11eb-866a-e5de98b96a0b.gif)

2021-01-01 19:00 UTC, smaranjitghose commented
Please pull the recent changes to the upstream repo

2021-01-02 17:36 UTC, anushbhatia approved these changes

2021-01-03 09:20 UTC, smaranjitghose requested changes

2021-01-03 09:20 UTC, smaranjitghose commented on index.html
> +                  href="resume.png" target="blank"
It is a thumb role to have resumes in PDF

2021-01-03 09:20 UTC, smaranjitghose commented on index.html
> +                  href="resume.png" target="blank"
Always put the images inside the `assets/images/home` directory for better management of assets

2021-01-06 11:53 UTC, merged