Fixed issues "Research Page Card Modification: Fonts"
smaranjitghose/awesome-portfolio-websites pull request #452
Opened 2021-01-09 10:31 UTC by RitikPandey1

**Proposed Changes**
Title: Semi Bold
Authors: Medium
Conference: Regular
Issue #423
for font weight values reference : https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

2021-01-09 11:05 UTC, vidhi-mody requested changes

2021-01-09 11:05 UTC, vidhi-mody commented on assets/css/research.css
> +     font-weight: 600;  /*semi-bold*/
Please remove the extra whitespace.

2021-01-09 11:05 UTC, vidhi-mody commented on assets/css/research.css
> +     font-weight: 400; /* regular */
Please remove the extra whitespace.

2021-01-09 11:17 UTC, RitikPandey1 commented on assets/css/research.css
> +     font-weight: 600;  /*semi-bold*/
done

2021-01-09 11:18 UTC, RitikPandey1 commented on assets/css/research.css
> +     font-weight: 400; /* regular */
done

2021-01-09 12:23 UTC, smaranjitghose commented
Use Poppins as the font please

2021-01-09 12:24 UTC, smaranjitghose commented
While doing multiple changes that end up in a single PR, try to rebase them and squash the commits into a single commit. Makes the code more readable in long term!

2021-01-09 13:18 UTC, RitikPandey1 commented
> Use Poppins as the font please

done 👍

2021-01-09 13:20 UTC, RitikPandey1 commented
> While doing multiple changes that end up in a single PR, try to rebase them and squash the commits into a single commit. Makes the code more readable in long term!

I don't know how to rebase the commits ,could you please tell me or refer some article

2021-01-09 13:30 UTC, smaranjitghose commented
[An article on Rebase](https://medium.com/osedea/git-rebase-powerful-command-507bbac4a234)
[Squash Commits](https://gist.github.com/patik/b8a9dc5cd356f9f6f980)

2021-01-09 13:33 UTC, RitikPandey1 commented
> [An article on Rebase](https://medium.com/osedea/git-rebase-powerful-command-507bbac4a234)
> [Squash Commits](https://gist.github.com/patik/b8a9dc5cd356f9f6f980)

Thanks ! 👍

2021-01-09 13:43 UTC, RitikPandey1 commented
> While doing multiple changes that end up in a single PR, try to rebase them and squash the commits into a single commit. Makes the code more readable in long term!

done

2021-01-11 17:14 UTC, anushbhatia requested changes
Add bold font to buttons too.

2021-01-13 12:21 UTC, smaranjitghose commented on assets/css/research.css
>  @import url('https://fonts.googleapis.com/css2?family=Londrina+Outline&display=swap');
I guess this is no longer required

2021-01-13 12:44 UTC, RitikPandey1 commented on assets/css/research.css
>  @import url('https://fonts.googleapis.com/css2?family=Londrina+Outline&display=swap');
okay, I removed it

2021-01-14 17:58 UTC, merged