Improved Footer Design
smaranjitghose/awesome-portfolio-websites pull request #477
Opened 2021-01-15 16:40 UTC by Priyanshu-official

Improved Footer Design #470 
Used normal CSS and Bootstrap

Design in black mode

![footer](https://user-images.githubusercontent.com/55912091/104753733-66f8a880-577e-11eb-932c-51a6cb82f683.png)

2021-01-15 16:42 UTC, Priyanshu-official commented
@smaranjitghose Pls Review PR and let me Know any changes needed

2021-01-15 18:44 UTC, smaranjitghose commented on .vscode/settings.json
> +    "liveServer.settings.port": 5502
Remove this and add it to .gitignore please

2021-01-15 18:45 UTC, smaranjitghose commented
![responsiveee](https://user-images.githubusercontent.com/46641503/104766033-e3e04e00-578f-11eb-8951-2635f577f51e.jpg)
There is an issue with responsiveness. Could you please fix this^^

2021-01-15 18:53 UTC, smaranjitghose requested changes

2021-01-15 18:53 UTC, smaranjitghose commented on assets/css/style.css
>  /*Footer*/
Make District Comments like

/*-----------------
FOOTER SECTION
-------------------*/

2021-01-15 18:53 UTC, smaranjitghose commented on assets/css/style.css
> -  clear: both !important;
Add  relevant comments

2021-01-15 18:53 UTC, smaranjitghose commented on assets/css/style.css
> +.rounded-social-buttons .social-button.twitter:hover, .rounded-social-buttons .social-button.twitter:focus {
Add Relevant comments

2021-01-15 18:53 UTC, smaranjitghose commented on assets/css/style.css
> +/* FORM CSS*/
Add meaning full comments like "Contact Form in Footer"

2021-01-16 03:56 UTC, Priyanshu-official commented
Ok💯

2021-01-16 12:12 UTC, Priyanshu-official commented
@smaranjitghose Sir Can pls Review this I check Responsive is Working fine for me

![MG1](https://user-images.githubusercontent.com/55912091/104811525-25b9d480-5822-11eb-9b6f-dc792ab08574.png)

![IP1](https://user-images.githubusercontent.com/55912091/104811527-281c2e80-5822-11eb-9ffd-cd1d58f1806f.png)

2021-01-16 12:46 UTC, Priyanshu-official commented
@smaranjitghose If everything is fine then Pls added both Label DWOC and SWOC if possible

2021-01-17 08:50 UTC, anushbhatia requested changes
Transitions in GitHub is really weird and it moves to the right of it. Add a minimal hover effect on it

2021-01-17 08:54 UTC, smaranjitghose commented
@Priyanshu-official  Neither the social media icons nor the quote in the footer is centre aligned in the mobile view

2021-01-17 08:55 UTC, smaranjitghose commented
Also, can you pull the current changes from master and incorporate them

2021-01-17 09:02 UTC, Priyanshu-official commented
@smaranjitghose sorry I didn't notice they are not center I will do it

2021-01-17 11:03 UTC, Priyanshu-official commented
@smaranjitghose Pls Review PR I have fixed all Responsive issue

2021-01-17 16:41 UTC, anushbhatia requested changes
Create a new PR because files have been modified
Add footer in app.js

2021-01-17 16:42 UTC, closed without merging

2021-01-17 16:44 UTC, anushbhatia commented
![color palllete](https://user-images.githubusercontent.com/40017559/104849746-65abb500-5911-11eb-8970-278734613304.jpg)

2021-01-18 08:50 UTC, Priyanshu-official commented
@anushbhatia Ok Is Everything is fine in the footer Just I have to move the code to the app.js File Right??