Added navbar mobile view transition
smaranjitghose/awesome-portfolio-websites pull request #489
Opened 2021-01-18 13:27 UTC by Harshita-Kanal

### Description
Added transition for mobile view navigation bar. 
Fixes #483 
### Screenshot
![John Doe _ Home](https://user-images.githubusercontent.com/41537515/104920911-8ed64f00-59be-11eb-9eff-6d6a7cbed80b.gif)

2021-01-18 19:34 UTC, smaranjitghose requested changes

2021-01-18 19:34 UTC, smaranjitghose commented on assets/css/home.css
>  }
This has to be in ``style.css`` to be called on all other pages as well

2021-01-18 19:34 UTC, smaranjitghose commented
![navvv](https://user-images.githubusercontent.com/46641503/104956526-4fc1f100-59f2-11eb-98fe-4e6a4f8267a4.jpg)
Can you please remove the outline or border

2021-01-18 19:53 UTC, smaranjitghose commented
@anushbhatia any color related suggestions or perhaps for the on hover transitions?

2021-01-19 06:20 UTC, anushbhatia commented on assets/css/home.css
> +  box-shadow: 0 2px 5px rgba(255, 101, 47, .2);
Add a box shadow of black red looks pretty weird on this page

2021-01-19 10:20 UTC, Harshita-Kanal commented
I have made the required changes, I was also able to implement the animation as per the reference given in the issue, please check it out as well, fixed the toggling of the navbar as well in  some pages by adding the jquery and popper cdn links in script section.
![John Doe _ Home (1)](https://user-images.githubusercontent.com/41537515/105020879-e089e280-5a6d-11eb-97c9-713ec1b2e4ae.gif)

2021-01-19 11:29 UTC, smaranjitghose commented on assets/js/app.js
> -	bodyElement.append(footer);
Keep the indentation  constant for all function definations

2021-01-19 12:10 UTC, Harshita-Kanal commented
Fixed the indentation.

2021-01-20 07:22 UTC, anushbhatia approved these changes

2021-01-20 14:44 UTC, smaranjitghose commented
In a follow up PR, make sure the side bar extends to the entire screen on hover/click as done [here](https://girlscriptboilerplate.netlify.app/)

2021-01-20 14:44 UTC, merged

2021-01-20 14:44 UTC, smaranjitghose commented
Great work with clean code @Harshita-Kanal !

2021-01-20 18:49 UTC, Harshita-Kanal commented
Thanks 🙂