SideNav Hamburger Animation #519
smaranjitghose/awesome-portfolio-websites pull request #528
Opened 2021-02-01 13:57 UTC by Chaitanya31612

Added given hamburger navbar toggler into app.

2021-02-01 18:09 UTC, smaranjitghose commented
![hamb](https://user-images.githubusercontent.com/46641503/106499553-bd881580-64e6-11eb-9479-9d11d1b059ef.jpg)
Icon is not displaying

2021-02-01 18:10 UTC, smaranjitghose approved these changes

2021-02-02 05:26 UTC, Chaitanya31612 commented
> ![hamb](https://user-images.githubusercontent.com/46641503/106499553-bd881580-64e6-11eb-9479-9d11d1b059ef.jpg)
> Icon is not displaying

![image](https://user-images.githubusercontent.com/54992097/106556282-31590b00-6545-11eb-858a-fa1e13402fa7.png)
Strange, it's coming for me and the animation is also working as expected.

2021-02-02 16:07 UTC, smaranjitghose commented
![side_nav](https://user-images.githubusercontent.com/46641503/106627518-e4a21e00-659e-11eb-97ac-42ec5ad3dd13.jpg)

2021-02-02 16:08 UTC, anushbhatia requested changes
![image](https://user-images.githubusercontent.com/40017559/106627536-e7047800-659e-11eb-9e34-7d0abb53f2d0.png)
Align to the right side of the header a

2021-02-02 16:23 UTC, anushbhatia requested changes
Put a comment like

``` terminal
/* 
---------------------------------
         TEXT ANIMATIONS
----------------------------------
*/
```
so the file is more readable 
Add comments like these

2021-02-03 13:38 UTC, smaranjitghose approved these changes

2021-02-03 13:38 UTC, smaranjitghose commented on assets/js/app.js
PLEASE PUT COMMENTS FOR FUNCTION DESCRIPTIONS.

2021-02-03 13:38 UTC, merged

2021-02-03 13:39 UTC, smaranjitghose commented
@Chaitanya31612 I am merging this PR.

If it's okay, I would ask you to give a PR and comment your code (document it) to make it more readable and explainable. This is also one of the goals of this project

2021-02-03 16:11 UTC, Chaitanya31612 commented
> @Chaitanya31612 I am merging this PR.
> 
> If it's okay, I would ask you to give a PR and comment your code (document it) to make it more readable and explainable. This is also one of the goals of this project

Sure, @smaranjitghose I'll make a pull request with comments for code I've written.