project card bug issue resolved
smaranjitghose/awesome-portfolio-websites pull request #547
Opened 2021-02-09 05:49 UTC by jatinjain001

I resolved the issue you can review my PR

2021-02-09 15:33 UTC, smaranjitghose requested changes

2021-02-09 15:33 UTC, smaranjitghose commented on assets/js/app.js
> -let footer = $(`
Please do not change the files not related to the task your assigned to complete

2021-02-09 15:33 UTC, smaranjitghose commented
![navbar](https://user-images.githubusercontent.com/46641503/107386499-ebd6a800-6b19-11eb-9482-ddd052ed7a61.jpg)

2021-02-09 15:34 UTC, closed without merging

2021-02-09 15:46 UTC, jatinjain001 commented
should i need to do again PR

2021-02-09 15:53 UTC, smaranjitghose commented
> should i need to do again PR

If you are continuing with the contribution to the issue, then yes

2021-02-09 15:59 UTC, jatinjain001 commented
okay

2021-02-10 18:33 UTC, jatinjain001 commented
Okay I am reaally sorry