Aboutme and skills page added and deleted the copyright code in files.
smaranjitghose/awesome-portfolio-websites pull request #559
Opened 2021-02-15 14:08 UTC by gupta31

As of now I made a page which gives more information about candidate(Introduction about myself)and skills which is essential to show in-front of any recruiter. I tried to fulfill it .

2021-02-15 17:06 UTC, smaranjitghose commented on assets/css/skins/color-1.css
> +
What is this for>?

2021-02-15 17:09 UTC, smaranjitghose requested changes

2021-02-15 17:09 UTC, smaranjitghose commented on index.html
> -    <link rel="stylesheet" href="assets/css/home.css">
Change only the parts of the code that related to feature addition or bug fix.

Otherwise it would result in merge conflicts for others

2021-02-15 17:09 UTC, smaranjitghose commented on index.html
> +        <span>Created By <a href="#">Smaranjit Ghosh</a>|<span class="far fa-copyright"></span>2021 All right reserverd. </span>
Do not keep unused code

2021-02-15 17:20 UTC, smaranjitghose commented
# Further Feedback:
- Refrain from using inline CSS as much as possible
- Just build the page and add a Link in the Navbar. Do not put any button on the home page ( The current one is weirdly placed)
- Please make sure your added changes are mobile responsive. That's one of the basic expectations from a web developer.
![ress](https://user-images.githubusercontent.com/46641503/107976304-589ce700-6fdf-11eb-92b0-33571c0fd1bc.jpg)
- The percentage of skills is not relevant. For example, if I have been working with Python for more than half a decade, it is next to impossible to quantify how much percentage of it, I know.
- Add logos of the technology
- Have separate sections for stacks related to Front End, Back End, DevOPs, Machine Learning, etc
- The `Hire Me` button doesn't make sense at all
- For the `Download  CV` button, add functionality to download the pdf on click

2021-02-15 17:20 UTC, closed without merging

2021-02-16 20:13 UTC, gupta31 commented
Noted your feeback.Can i upload this page by improving it further as you said?

2021-02-16 21:17 UTC, smaranjitghose commented
Sure. Raise a new PR.

2021-02-16 21:28 UTC, gupta31 commented
- Add logos of the technology(Added)
- Have separate sections for stacks related to Front End, Back End, DevOPs, Machine Learning, etc(You need separate sections like for frontend etc?? Please elaborate more as i am not getting properly. )
![feedback1](https://user-images.githubusercontent.com/48806247/108123168-75164d80-70cb-11eb-8da6-11d3237ad18f.PNG)

2021-02-16 21:59 UTC, smaranjitghose commented
> * Add logos of the technology(Added)
> * Have separate sections for stacks related to Front End, Back End, DevOPs, Machine Learning, etc(You need separate sections like for frontend etc?? Please elaborate more as i am not getting properly. )
>   ![feedback1](https://user-images.githubusercontent.com/48806247/108123168-75164d80-70cb-11eb-8da6-11d3237ad18f.PNG)

Further Feedback:

- Refer [this](https://ashutoshhathidara.com/#/home) for the understanding how we can organize our skills as per area of interest. Basically, the idea is to expand your resume visually! 
- The above reference is meant for giving a clear idea. Do not base your PR directly on it. We do not require those additional lines about the stack. Come up with your creative ideas
- The icons are self-explanatory, we do not need to put a text below to tell the audience what it is. 
- Visit [Sourcer](https://ashutoshhathidara.com/#/home). Ignore the SSL failure, it's a simple open-source [project](https://github.com/sourcerer-io/sourcerer-app) and most probably won't be up to anything fishy. After creating your profile, you'll notice it would give the no of lines of code one has written. We can store all the facts as JSON in a variable inside a skill.json and randomly display it over a card saying *Fun Fact*
```python

                                ------------------------------------------------
                             |                                                                        |
                             |    # Fun Fact about me:                                  |
                             |    "As per sourcerer, till date I have                |                                                         
                             | written around 40k lines in Python                |
                             |    across all my projects"                                |
                             |                                                                        |
                               ------------------------------------------------
````
*Ignore the markdown rendering. I hope you got the idea expressed*


## Experimental:

Try to create an interactive word cloud of the skills. [Reference](https://jacekjeznach.com/skills/)

2021-02-16 22:01 UTC, smaranjitghose commented
> * Add logos of the technology(Added)
> * Have separate sections for stacks related to Front End, Back End, DevOPs, Machine Learning, etc(You need separate sections like for frontend etc?? Please elaborate more as i am not getting properly. )
>   ![feedback1](https://user-images.githubusercontent.com/48806247/108123168-75164d80-70cb-11eb-8da6-11d3237ad18f.PNG)

Put the `download CV button` where the `About me` section 's  text ends