Scroll to top button (#665)
smaranjitghose/awesome-portfolio-websites pull request #724
Opened 2021-06-16 16:15 UTC by varunwho

### Scroll to top button

https://user-images.githubusercontent.com/53107832/122255536-d8828180-ceeb-11eb-8b3b-5608f0b37c58.mp4

2021-06-17 22:29 UTC, smaranjitghose requested changes

2021-06-17 22:29 UTC, smaranjitghose commented on assets/js/dynamicTitle.js
> -
Avoid these changes for now

2021-06-17 22:29 UTC, smaranjitghose commented on assets/js/app.js
> -
Add appropriate comments

2021-06-17 22:30 UTC, smaranjitghose commented
Reduce the size of the button by 25% of it's present size. The color of the button should be different while on the footer and on the remainder of the page

2021-06-18 02:45 UTC, varunwho commented
> Reduce the size of the button by 25% of it's present size. The color of the button should be different while on the footer and on the remainder of the page

Yup I will do it

2021-06-18 17:55 UTC, anushbhatia requested changes
On selection of the button avoid that black box around it if possible.

2021-06-20 06:45 UTC, varunwho commented
#665 
### **I've done these changes**
- Reduced the size
- Added the microanimation which was suggested
- Removed the outline which appeared after the click
- The color of the button changes when it hits the footer

2021-06-22 10:56 UTC, smaranjitghose commented
@varunwho This looks perfect. Just incorporate the recent changes to the project to remove the merge conflict.

2021-06-22 10:57 UTC, smaranjitghose approved these changes

2021-06-22 10:58 UTC, anushbhatia requested changes
When we move to the top of the page it should vanish automatically.

2021-06-23 05:23 UTC, varunwho commented
Ignore the latest commit here, I've made a new PR

2021-06-23 05:31 UTC, closed without merging