adding toggle button
smaranjitghose/awesome-portfolio-websites pull request #730
Opened 2021-06-16 20:51 UTC by SamikshaSankar

2021-06-17 22:26 UTC, smaranjitghose requested changes

2021-06-17 22:26 UTC, smaranjitghose commented on .vs/VSWorkspaceState.json
> +    "\\assets\\css",
Remove these files and gitignore them please~

2021-06-17 22:26 UTC, smaranjitghose commented on index.html
> -<!DOCTYPE html>
This change is not required😅

2021-06-17 22:26 UTC, smaranjitghose commented on assets/js/app.js
> +
Set the default theme to dark please

2021-06-17 22:26 UTC, smaranjitghose commented on assets/js/app.js
Add appropriate comments

2021-06-17 22:27 UTC, smaranjitghose commented
Overall nice work @SamikshaSankar .

@anushbhatia could you please help her out with the positioning and the UI enhancement of the toggle button.


Note: The color of the Research Page and the cards are hugely messed up in the dark mode.

2021-06-17 23:26 UTC, smaranjitghose commented
@SamikshaSankar Could you make use of [this](https://codepen.io/jh3y/details/LYNZwGm) for the toggle animation instead of the emojis

2021-06-22 11:17 UTC, smaranjitghose commented
Closed due to inactivity

2021-06-22 11:17 UTC, closed without merging

2021-06-22 11:25 UTC, SamikshaSankar commented
@smaranjitghose I am working on this issue