Alert Popup feature imported successfully in contact page
smaranjitghose/awesome-portfolio-websites pull request #736
Opened 2021-06-17 17:26 UTC by ROHAN842

I successfully added an alert which will pops up and will tell the user that message was delivered successfully with a green tick along with I also added a feature without back end with which user would be sent to a fresh new page on clicking Send button where the message is displayed as  "Thank you We received your submission , Return ".

https://user-images.githubusercontent.com/61961107/122445187-ed7c1500-cfbe-11eb-89e3-ef63e3d3ff12.mp4

2021-06-17 19:03 UTC, anushbhatia requested changes
https://user-images.githubusercontent.com/40017559/122457702-8e250180-cfcc-11eb-80b1-dafa915b2146.mp4

It should validate all fields before sending them to the next page. Still, it show's congrats so check these and add them.

2021-06-17 21:43 UTC, smaranjitghose requested changes

2021-06-17 21:43 UTC, smaranjitghose commented on assets/js/app.js
> +            swal("Congrats!", "Message was delivered successfully!", "success");
Make this as:

```
Thank you for the response. John will get in touch soon!
```

2021-06-18 13:58 UTC, ROHAN842 commented on assets/js/app.js
> +            swal("Congrats!", "Message was delivered successfully!", "success");
OK I will resolve this

2021-06-20 10:32 UTC, ROHAN842 commented
Hey @anushbhatia as you have already merged my updated PR so I request you to kindly close this PR

2021-06-20 13:33 UTC, closed without merging