Shaking hand
smaranjitghose/awesome-portfolio-websites pull request #768
Opened 2021-06-19 10:52 UTC by Pratham-Mishra178

2021-06-19 12:30 UTC, smaranjitghose requested changes

2021-06-19 12:30 UTC, smaranjitghose commented on index.html
> +    <div class="text col-sm-6">Hi <span class="wave"><img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="35px"></span>&nbsp;,I'm <span class="header">John Doe</
The assets should be present locally

2021-06-19 13:44 UTC, Pratham-Mishra178 commented on index.html
> +    <div class="text col-sm-6">Hi <span class="wave"><img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="35px"></span>&nbsp;,I'm <span class="header">John Doe</
okay

2021-06-19 13:53 UTC, Pratham-Mishra178 commented on index.html
> +    <div class="text col-sm-6">Hi <span class="wave"><img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="35px"></span>&nbsp;,I'm <span class="header">John Doe</
content put in the assets.

2021-06-19 15:43 UTC, smaranjitghose commented
![respon](https://user-images.githubusercontent.com/46641503/122647694-22b17000-d143-11eb-9aa8-b296d995e0b1.png)
 Responsiveness Issue for screen sizes similar to Pixel 2 XL

2021-06-20 02:54 UTC, Pratham-Mishra178 commented
> ![respon](https://user-images.githubusercontent.com/46641503/122647694-22b17000-d143-11eb-9aa8-b296d995e0b1.png)
> Responsiveness Issue for screen sizes similar to Pixel 2 XL

ok resolving it

2021-06-20 02:59 UTC, Pratham-Mishra178 commented
![Screenshot (504)](https://user-images.githubusercontent.com/78583437/122660768-8a96a380-d1a1-11eb-8750-8b5e8c44a1e5.png)

But it looks great at my place

2021-06-20 03:24 UTC, Pratham-Mishra178 commented
Now its looking great, Check it

2021-06-22 11:15 UTC, smaranjitghose approved these changes

2021-06-22 11:15 UTC, merged