Modified footer contact form
smaranjitghose/awesome-portfolio-websites pull request #773
Opened 2021-06-20 18:15 UTC by Chaitalishetty

2021-06-20 20:10 UTC, smaranjitghose commented
The vertical space between each form element should be the same as it is present in the hosted version of the website. Please rectify that

2021-06-21 11:39 UTC, Chaitalishetty commented
I have changed the animation that is responsive for all the screens. Is it fine or should i make any changes?

2021-06-22 10:18 UTC, smaranjitghose requested changes

2021-06-22 10:18 UTC, smaranjitghose commented on assets/css/style.css
> +>>>>>>> f16ce2f2466ece18f2c52bed883fb862cd57603b
Remove these. Please be mindful while merging

2021-06-22 10:18 UTC, smaranjitghose commented on assets/css/style.css
> +=======
Remove these. Please be mindful while merging

2021-06-22 10:40 UTC, smaranjitghose commented
Responsiveness Issue still persists on multiple screen sizes:

|          |         |  
| ------|------|
|     ![Respons_7](https://user-images.githubusercontent.com/46641503/122910419-c84b2600-d373-11eb-9411-29fda6733bd4.png)     |  ![Respons_6](https://user-images.githubusercontent.com/46641503/122910424-c97c5300-d373-11eb-8081-8c6772930ec6.png)     |          
|    ![Respons_3](https://user-images.githubusercontent.com/46641503/122910429-caad8000-d373-11eb-8fdb-9c67263a0e5f.png)      |     ![Respons_2](https://user-images.githubusercontent.com/46641503/122910431-cb461680-d373-11eb-9bb3-52ded7e40689.png)   |              
|![Respons_4](https://user-images.githubusercontent.com/46641503/122910427-ca14e980-d373-11eb-9254-d5f3b507e63d.png) | ![Respons_5](https://user-images.githubusercontent.com/46641503/122910426-ca14e980-d373-11eb-9978-e5ca92484c13.png)   | 
| ![Respons_1](https://user-images.githubusercontent.com/46641503/122910434-cb461680-d373-11eb-95b9-8e17939c3592.png)    | |

2021-06-22 10:41 UTC, smaranjitghose commented
Raise a new PR for this

2021-06-22 10:41 UTC, closed without merging