Changes made to the footer submit button in projects file
smaranjitghose/awesome-portfolio-websites pull request #782
Opened 2021-06-23 11:07 UTC by riya123-hub

2021-06-23 16:11 UTC, smaranjitghose requested changes

2021-06-23 16:11 UTC, smaranjitghose commented on assets/css/project.css
>  html[data-theme = 'light']
Remove this additional line.

Git ignore the .DS_Store file

2021-06-23 16:12 UTC, smaranjitghose commented
The button itself looks cool but does not go well with the rest of the theme.

@anushbhatia  could you please give some suggestions for the same

2021-06-23 16:22 UTC, riya123-hub commented
> The button itself looks cool but does not go well with the rest of the theme.
> 
> * Please follow the first reference given in the corresponding issue
> * The code should be well documented (Add comments wherever necessary)
> * The PR description should mention the issue number as well as a snapshot/clip of the demo after your changes

Okay I will try to make the requested updates done

2021-06-24 14:39 UTC, deeqakkk reviewed
okay, it's fine @riya123-hub

2021-06-24 19:00 UTC, smaranjitghose commented
Closed as the PR is not as per the requirement even post a review.

2021-06-24 19:00 UTC, closed without merging