'Footer_Form_Microanimation'
smaranjitghose/awesome-portfolio-websites pull request #831
Opened 2021-06-28 15:17 UTC by shreyanshu07

Here I have added Microanimation from the below link
https://codepen.io/MichaelArestad/pen/ohLIa
I have matched the color theme with the website and checked the reponsiveness was same .
![image_2021-06-28_204535](https://user-images.githubusercontent.com/72155853/123661025-cee50c00-d851-11eb-9ee8-e35cadf15779.png)
![image_2021-06-28_204629](https://user-images.githubusercontent.com/72155853/123661123-eb814400-d851-11eb-8923-16e9153ff3e4.png)

2021-06-28 18:17 UTC, smaranjitghose commented
## Feedback:
- Please have a look at the entire micro animation.
- The color of the labels i.e. Name, Email, and Message (this missing) should be the same as that of the Send Button.
- Unresponsive for certain mobile screens:

![Mobile_Footer](https://user-images.githubusercontent.com/46641503/123684501-293e9680-d86b-11eb-8d97-af6055b98c33.png)

2021-06-28 18:20 UTC, smaranjitghose requested changes

2021-06-28 18:20 UTC, smaranjitghose commented on assets/css/Check.css
> +
What is this file for?

2021-06-28 18:20 UTC, smaranjitghose commented on assets/css/Check.css
> +#yourName {
Name the variables judiciously!

2021-06-28 18:20 UTC, smaranjitghose commented on assets/js/app.js
>                  <form>
The above files are renamed without any requirement leading to error in other sections

2021-06-28 18:20 UTC, smaranjitghose commented on assets/js/app.js
> +  <span>
Use a Linter please. This is poorly written

2021-06-28 18:20 UTC, smaranjitghose commented on assets/js/app.js
> +    <input class="skinnyx" id="yourEmail" type="email" placeholder="Enter your Email-id" /><label for="EmailId">Email</label>
Name the classes judiciously!

2021-06-29 04:46 UTC, shreyanshu07 commented
I have made the following changes :-
1. Changed the names of variables , classes
2. Gave proper indentation in the code
3. Removed the unwanted header files in my check.css file
4. Changed the color of label according to the requirements.
5. Added the same to the "Message" field

2021-06-29 15:15 UTC, shreyanshu07 commented
@deeqakkk 
![image](https://user-images.githubusercontent.com/72155853/123823509-e805bf80-d91a-11eb-9318-2fe02717fb44.png)

2021-06-29 15:18 UTC, shreyanshu07 commented
![image](https://user-images.githubusercontent.com/72155853/123823942-3e72fe00-d91b-11eb-8e24-0a8225466ea3.png)
@deeqakkk I think now it's perfect :-)

2021-06-29 16:54 UTC, smaranjitghose commented
Still not mobile responsive

2021-06-29 18:06 UTC, shreyanshu07 commented
![image](https://user-images.githubusercontent.com/72155853/123846269-c6183700-d932-11eb-8804-6f29a62d6beb.png)
@smaranjitghose

2021-07-08 17:03 UTC, closed without merging