fixed issue #884
smaranjitghose/awesome-portfolio-websites pull request #888
Opened 2021-07-06 11:05 UTC by monishamandal02

I had done all the modifications which had been asked. Please check :)

2021-07-06 11:59 UTC, smaranjitghose commented
# Feedback:

The background color of the cards are to be changed to a shade of black/gray for dark mode as well

### Current Version

![Change_color_of_cards](https://user-images.githubusercontent.com/46641503/124595971-513b8480-de7f-11eb-8271-9c2f778cb0ab.png)

### Sample Requirement:

![Colot_Tr](https://user-images.githubusercontent.com/46641503/124596063-6dd7bc80-de7f-11eb-896c-0f2533dab40b.png)

[Hacktoberfest Reference](https://hacktoberfest.digitalocean.com/)

2021-07-07 15:44 UTC, smaranjitghose requested changes

2021-07-07 15:44 UTC, smaranjitghose commented on assets/css/education.css
> +    --bg1-color: #000033;
Please have a look at the reference I gave, inspect the website and get the colors. The entire point of changing this is to make sure that the cards are visible separately from the background color

2021-07-07 15:44 UTC, smaranjitghose commented on assets/js/education.js
> +            <div class="content">
Unnecessary Indentation Change. Please revert this

2021-07-07 15:44 UTC, smaranjitghose commented on assets/css/education.css
> +    font-family: "NHaas";
Remove this and use Inter Font please

2021-07-07 15:44 UTC, smaranjitghose commented on assets/css/education.css
>  }
Declare one variable for background color and another for card color

2021-07-07 15:44 UTC, smaranjitghose commented on assets/css/education.css
> +    color: var(--font-color);
the Font color is not be used for this 😅

2021-07-07 15:44 UTC, smaranjitghose commented on assets/css/education.css
> +    background-color: var(--bg1-color);
Use card color for this and not the background color

2021-07-07 15:46 UTC, smaranjitghose commented
Please define the variables in the CSS files for the following and use the corresponding values as specified

- Background Color: #072540 (Dark Mode)
- Element Color: #93c2db (Dark Mode)
- Font Color: #0069ff (Light Mode)
- Illustration Color: #0069ff (Light Mode)


- Font: Inter

2021-07-07 15:49 UTC, smaranjitghose commented on assets/css/education.css
>  /* Dark and Light theme */
This is a self-explanatory part of the stylesheet. Could you please remove this comment and all spaces before this

2021-07-07 15:52 UTC, smaranjitghose commented
![color_shadow](https://user-images.githubusercontent.com/46641503/124791067-5bd24880-df69-11eb-9cb0-38ec007e6307.png)
Do not add a color to the shadow please

2021-07-08 16:59 UTC, smaranjitghose commented
@monishamandal02 I have already given the feedback for this PR. Please incorporate the suggested changes and let me know.

2021-07-09 08:43 UTC, anushbhatia requested changes
Box shadow is too large avoid that cause it looks like a black border rather than shadow

2021-07-09 21:49 UTC, smaranjitghose commented
@monishamandal02 Any updates?

2021-07-10 16:52 UTC, monishamandal02 commented
I have removed the extra changes like the blue shadow, fonts and all. I am lagging with some knowledge I couldn't switch the colour of cards, mooc cards after using the dark-light switch.

2021-07-11 18:27 UTC, anushbhatia commented
> I have removed the extra changes like the blue shadow, fonts and all. I am lagging with some knowledge I couldn't switch the colour of cards, mooc cards after using the dark-light switch.

Could you share exactly where are you lagging and contact us on the relevant platform to resolve this. Also for dark mode different colour variables are already defined just check how to use them

2021-07-31 16:57 UTC, closed without merging