Open source Card
smaranjitghose/awesome-portfolio-websites pull request #891
Opened 2021-07-08 03:44 UTC by ujju20

I have added roughly open source cards just wanted that am I going right?
Also, I am unable to show images even I am giving the right path.

2021-07-08 16:52 UTC, smaranjitghose requested changes

2021-07-08 16:52 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +          title: "GirlScript Summer Of Code 2020",
[Sample Reference for using assets like images](https://github.com/smaranjitghose/doc2pen/blob/master/src/pages/Home/sections/OpenSource/OpenSource.jsx)

2021-07-08 16:52 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +          cardImage: "src/assets/images/open-source/2.jpg",
Have a look at the above reference for the structure of pages and the corresponding sections.

Restructure this into the open-source section. 

Try to use JSX

2021-07-08 16:52 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +                    <path id="Vector_105" opacity="0.1" d="M188.013 248.448C188.013 248.448 183.732 248.198 183.9 249.356L188.013 248.448Z" fill="black"></path>
Define this in a separate component called top_illus

2021-07-09 21:47 UTC, smaranjitghose commented
@ujju20 Any updates?

2021-07-10 01:49 UTC, ujju20 commented
> @ujju20 Any updates?

Ya, I am doing it I will push changes today itself.

2021-07-12 10:55 UTC, ujju20 commented
I am Uable to render topIlus in the experience.js file I don't know why it is not getting rendered.

2021-07-12 20:58 UTC, anushbhatia reviewed
![image](https://user-images.githubusercontent.com/40017559/125354870-f247a500-e381-11eb-8e24-b7ae4fad353d.png)
 it is rendered have a look in the deployment. The functionality may not work cause code has not been integrated

2021-07-12 21:00 UTC, smaranjitghose commented
> I am Unable to render topIlus in the experience.js file I don't know why it is not getting rendered.

For now, that is not your responsibility. You have to make sure that when we visit the `/research` path, we can see the heading "Open Source" followed by the cards of the design as requested in the corresponding issue description. The cards should be mobile responsive, have real data instead of lorem ipsum, and be injected dynamically by updating the value of a variable

2021-07-12 21:00 UTC, smaranjitghose commented
I have 1 more day for this

2021-07-13 02:18 UTC, ujju20 commented
> I have 1 more day for this
Ok I have made the changes 
Check them.

2021-07-13 02:18 UTC, ujju20 commented
Ok I have made the changes
Check them.

2021-07-13 03:33 UTC, anushbhatia commented
Deploy is failing check if there are any warnings in your code remove them if any.

2021-07-13 07:06 UTC, ujju20 commented
There was one warning I have fixed that 
see this 
![Screenshot from 2021-07-13 12-35-22](https://user-images.githubusercontent.com/64632969/125406830-e0442180-e3d6-11eb-8c87-2a172143764f.png)

2021-07-13 16:58 UTC, ujju20 commented
Have You reviewed my PR?

2021-07-13 18:43 UTC, smaranjitghose commented
Why is the old UI used for this? Even after having given detailed description in the corresponding issue.

2021-07-13 18:43 UTC, closed without merging