Conference Highlight Page Template
smaranjitghose/awesome-portfolio-websites pull request #895
Opened 2021-07-08 17:39 UTC by padmajabhol

2021-07-08 18:35 UTC, smaranjitghose requested changes

2021-07-08 18:35 UTC, smaranjitghose commented on assets/css/conf_temp.css
> +@import url(//fonts.googleapis.com/css?family=Lato:300:400);
Could you please use Inter or Poppins?

2021-07-08 18:35 UTC, smaranjitghose commented on assets/css/conf_temp.css
> +
Remove the extra spaces please

2021-07-08 18:35 UTC, smaranjitghose commented on experience.html
> -                  <path id="Vector_48" d="M160.89 54.1505H150.244C149.568 54.1505 149.02 54.6987 149.02 55.3749V55.5837C149.02 56.2599 149.568 56.808 150.244 56.808H160.89C161.566 56.808 162.114 56.2
Avoid the linting/indentation changes for now

2021-07-08 18:38 UTC, smaranjitghose commented
## General Feedback:

- Make sure to link the issue in the PR description
- Add a clip/snapshot of the changes in the PR description.

## Issue Specific Feedback:

- Please have a look at the reference provided in the Issue Description. The changes proposed by this PR do not remotely satisfy the requirements of the image slider UI requested.


If you wish to continue with the mentioned UI, do let us know

2021-07-08 18:38 UTC, closed without merging

2021-07-08 19:52 UTC, padmajabhol commented
> ## General Feedback:
> * Make sure to link the issue in the PR description
> * Add a clip/snapshot of the changes in the PR description.
> 
> ## Issue Specific Feedback:
> * Please have a look at the reference provided in the Issue Description. The changes proposed by this PR do not remotely satisfy the requirements of the image slider UI requested.
> 
> If you wish to continue with the mentioned UI, do let us know

The reference carousel had a different classname for each card , I talked about it to one of the project admins and he said it was fine if I wanted to work on a different UI but it was important to make the data dynamic. I can make the exact UI you asked for but it won't be able to render the data dynamically.

2021-07-09 05:04 UTC, anushbhatia commented
Do mention this stuff in the description when you generate a PR so that PA's will know everything about it.

2021-07-09 07:38 UTC, padmajabhol commented
> Do mention this stuff in the description when you generate a PR so that PA's will know everything about it.

I ll be more careful next time.