Expereince card section
smaranjitghose/awesome-portfolio-websites pull request #910
Opened 2021-07-11 06:59 UTC by Anita-ihuman

Created the experience page in react.js.

2021-07-11 12:34 UTC, smaranjitghose commented on src/pages/Experience/Experience.css
> +  color: #4e00bb;
Please define variables for this

2021-07-11 12:34 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +          text: "Contributed to rollout of upgraded DEFSafe platform, delivering the company’s first persistent, end-to-end data protection that allow users to control security protocols across multi
A single line should work.

2021-07-11 12:46 UTC, smaranjitghose requested changes

2021-07-11 12:46 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +// AOS.init();
This is not required for now

2021-07-11 12:46 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +          text: " Created a modern new interface that contributed to a 15% increase in new user adoption rates within one month of rollout",
Single text input should work.

2021-07-11 18:29 UTC, anushbhatia reviewed
Avoid all the warnings before deploying also to import images see the relevant standards in react and you will be able to deploy it successfully.

2021-07-12 06:24 UTC, Anita-ihuman commented
@anushbhatia I don't know why the Vercel deployment is failing. Can you help me, please

2021-07-12 20:48 UTC, smaranjitghose commented on src/pages/Experience/Experience.css
> +  background: white;
Define the colors for the CSS in variables please

2021-07-12 20:48 UTC, smaranjitghose commented on src/pages/Experience/Experience.js
> +};
Check if the last semi-colon leads to any warning please

2021-07-12 21:05 UTC, anushbhatia commented
> @anushbhatia I don't know why the Vercel deployment is failing. Can you help me, please

Check the warnings present in the vs code's 
![image](https://user-images.githubusercontent.com/40017559/125355550-cd076680-e382-11eb-9671-a8cd4e94449d.png)
The sample image is attached below here instead of the red icons there might be yellow warnings symbols to see how to resolve them and then you will be able to resolve it. Or contact me on slack or discord regarding this will help you with it.

2021-07-13 18:58 UTC, smaranjitghose requested changes

2021-07-13 18:58 UTC, smaranjitghose commented on src/pages/Experience/Experience.css
> +  background: rgb(255, 255, 255);
use variables for defining colors. Check out the master branch code

2021-07-13 18:58 UTC, smaranjitghose commented on src/pages/Experience/Experience.css
> +.card1 {
name these classes appropriately

2021-07-13 19:01 UTC, smaranjitghose commented
![Responsivenss_Bug](https://user-images.githubusercontent.com/46641503/125509950-899e1296-f59f-4ce5-a7df-7d1d1b9cd272.png)
Multiple Responsiveness Bug

2021-07-13 19:01 UTC, closed without merging