back-to-top Fix
smaranjitghose/awesome-portfolio-websites pull request #926
Opened 2021-07-13 04:29 UTC by AmanBisht01

[ Done ] The to top button's position should be dynamic w.r.t location of the page
[ Done ] On click, it should take us to the topmost section of each page
[ Done ] It should not appear on mobile screens
[ Done ] It should not appear on the top of the page (or in fact midway)

2021-07-13 18:50 UTC, smaranjitghose requested changes

2021-07-13 18:50 UTC, smaranjitghose commented on src/components/Footer/Footer.css
> +  background-color: #121212;
Use variables for the colors. Name them appropriately. Declare separately for dark mode and light mode. Check the style.css in the master branch please

2021-07-13 18:50 UTC, smaranjitghose commented on src/components/Footer/Footer.css
> -    border-left-style: none;
Undo all the indentation/linting changes please

2021-07-13 18:50 UTC, smaranjitghose commented on src/components/Footer/Footer.js
> +  useEffect(() => {
Add comments please. Poorly documented code is of no use in the long term

2021-07-13 18:52 UTC, smaranjitghose commented on src/components/Footer/Footer.js
> -    window.scrollTo({
Undo all these linting/indentation changes

2021-07-13 18:52 UTC, smaranjitghose commented on src/components/Footer/Footer.js
> +                id="Layer_1"
Undo these linitng/indentation changes

2021-07-14 15:14 UTC, AnirudhPanda commented
Are you resolving the merge conflicts on this @AmanBisht01 ?

2021-07-14 15:20 UTC, AmanBisht01 commented
@AnirudhPanda Resolved conflicts.

2021-07-16 12:08 UTC, merged