Expereince card section
smaranjitghose/awesome-portfolio-websites pull request #935
Opened 2021-07-14 11:36 UTC by Anita-ihuman

Fixes #923 

# Work Done:

- Fixed Responsiveness bug in the Experience card section
- Made adjustments to the image sizes

# Relevant Screenshots/Gifs

![Screenshot 2021-07-14 at 12 35 29](https://user-images.githubusercontent.com/62384659/125615609-e23b1bbd-0260-4730-98ba-4c026302e28c.png)

2021-07-14 12:24 UTC, smaranjitghose commented on src/components/Navbar/Navbar.css
> +    position: sticky;
We need the navbar to be visible when we scroll through the page

2021-07-14 12:24 UTC, smaranjitghose commented on src/pages/Experience/Experience.css
> +  color: var(--meta-col);
Where is the value for this defined in the stylesheet?

2021-07-14 12:32 UTC, smaranjitghose commented
Huge improvement over last PR @Anita-ihuman . Kudos to you for that.

## Further Feedback:

- The page is unresponsive for mobile screens. Please try to fix that issue

![unresponsive](https://user-images.githubusercontent.com/46641503/125621608-c13c108f-b499-4fe3-9187-cc8120638f59.png)


- Make the size of the image on the card smaller and square in shape so that more space is allocated for the text., Make the company title Bold/Black, shift the duration towards right, use bullet points


![UI_update](https://user-images.githubusercontent.com/46641503/125622462-56ce7ded-d880-46f0-b537-08b56580a32c.png)

- The navbar should be visible while scrolling through the website

2021-07-15 18:39 UTC, anushbhatia commented on src/pages/Experience/Experience.js
> +                      <span className="duration">{item.time}</span>
float right the date so it won't get stickup with the role tag

2021-07-15 18:41 UTC, anushbhatia requested changes
For very small mobile devices it might not have a container so you can add a container from bootstrap using that and then it will be good to go.

![image](https://user-images.githubusercontent.com/40017559/125840548-60a1bf69-2650-4d27-a2c2-857d977805ab.png)

2021-07-17 20:27 UTC, anushbhatia requested changes
![image](https://user-images.githubusercontent.com/40017559/126048646-26e0f79e-a106-440e-a692-c282ab7a2afd.png)
Check this resolution and solve the merge conflict then you are go to be merged

2021-07-19 08:05 UTC, smaranjitghose commented
- The cards are unresponsive for certain mobile screens as shown above
![unrep](https://user-images.githubusercontent.com/46641503/126124841-00d47632-16c6-4b68-aaaa-f03960dd789c.png)

- Make the logos square in size

2021-07-31 16:58 UTC, closed without merging