made navbar responsive in mobile and added border animation on navbar sections
smaranjitghose/awesome-portfolio-websites pull request #981
Opened 2021-07-17 12:35 UTC by GiotisK

## Corresponding Issues:
fixes #859 and #975

## PR Summary:
- Added hambuger button (as component) and toggle animation (as referenced in the issue)
- Added dropdown animation using the AnimatedHeight library (height animations with pure css are difficult to implement)
- Added border hover animation that fixes issue -> #975
- Cleaned up the Navbar.js  component code
- Added color variables

## Outcome Video:  

https://user-images.githubusercontent.com/10963096/126037024-49480c4b-2d22-4b62-90d2-da4bbed0738c.mp4

2021-07-17 12:39 UTC, GiotisK commented
Not sure what caused the failed deployment. Can you check it and let me know so I can fix it? Thank you

2021-07-17 20:17 UTC, anushbhatia requested changes
Add the hamburger files in the components folder and pull it in navbar

2021-07-17 20:20 UTC, anushbhatia reviewed
Great Work with the comments 😎

2021-07-17 20:20 UTC, anushbhatia commented on src/components/Navbar/HambugerButton.js
> +        <div onClick = {props.onClick} className={`hamburger ${props.activated ? 'is-active' : ''}`} id="hamburger-6">
why id= hamburger-6 can't it be hamburger

2021-07-18 17:12 UTC, GiotisK commented
@anushbhatia I've done the changes you proposed ! 🚀

2021-07-19 07:51 UTC, smaranjitghose approved these changes

2021-07-19 07:53 UTC, merged